##Numpy Basics

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,2,6,5]])

In [3]:
myarr

array([[3, 2, 6, 5]])

In [4]:
zero = np.zeros((2,5))

In [5]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
rng = np.arange(15)

In [7]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
linespace = np.linspace(1,5,7)

In [10]:
linespace

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [12]:
iden = np.identity(15)

In [13]:
iden

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [15]:
myarr.reshape(4,1)

array([[3],
       [2],
       [6],
       [5]])

In [16]:
myarr.shape

(1, 4)

Pandas Basics

In [18]:
import pandas as pd

In [19]:
dict1={
    "name":['keyur','sandesh','pratik','chinmay'],
    "marks":['95','80','85','75'],
    "city":['mumbai','nagpur','delhi','pune']
}

In [20]:
df=pd.DataFrame(dict1)

In [21]:
df

name marks    city
0    keyur    95  mumbai
1  sandesh    80  nagpur
2   pratik    85   delhi
3  chinmay    75    pune

In [22]:
df.index=[1,2,3,4]

In [23]:
df

name marks    city
1    keyur    95  mumbai
2  sandesh    80  nagpur
3   pratik    85   delhi
4  chinmay    75    pune

In [24]:
series=pd.Series(np.random.rand(20))

In [25]:
series

0     0.925838
1     0.310122
2     0.096091
3     0.501665
4     0.714917
5     0.890048
6     0.321988
7     0.610458
8     0.285421
9     0.111813
10    0.810752
11    0.369637
12    0.021034
13    0.353629
14    0.168107
15    0.299371
16    0.001316
17    0.183601
18    0.127558
19    0.080469
dtype: float64

In [26]:
type(series)

pandas.core.series.Series

In [28]:
newdf=pd.DataFrame(np.random.rand(334,5),index = np.arange(334))

In [29]:
newdf

0         1         2         3         4
0    0.400624  0.132076  0.223318  0.035703  0.762554
1    0.311540  0.345132  0.751883  0.365315  0.964518
2    0.661391  0.913564  0.580619  0.578853  0.489444
3    0.971994  0.725477  0.171128  0.670740  0.582053
4    0.881631  0.868961  0.173120  0.847732  0.222700
..        ...       ...       ...       ...       ...
329  0.833504  0.488470  0.638519  0.128384  0.921630
330  0.711398  0.888275  0.895772  0.535299  0.823657
331  0.018676  0.350492  0.622680  0.726020  0.975994
332  0.114657  0.763736  0.249243  0.564775  0.467320
333  0.965713  0.121478  0.341810  0.361453  0.267905

[334 rows x 5 columns]

In [30]:
newdf.head(5)

0         1         2         3         4
0  0.400624  0.132076  0.223318  0.035703  0.762554
1  0.311540  0.345132  0.751883  0.365315  0.964518
2  0.661391  0.913564  0.580619  0.578853  0.489444
3  0.971994  0.725477  0.171128  0.670740  0.582053
4  0.881631  0.868961  0.173120  0.847732  0.222700

In [31]:
newdf.tail(5)

0         1         2         3         4
329  0.833504  0.488470  0.638519  0.128384  0.921630
330  0.711398  0.888275  0.895772  0.535299  0.823657
331  0.018676  0.350492  0.622680  0.726020  0.975994
332  0.114657  0.763736  0.249243  0.564775  0.467320
333  0.965713  0.121478  0.341810  0.361453  0.267905

In [32]:
newdf.sort_index(axis=0)

0         1         2         3         4
0    0.400624  0.132076  0.223318  0.035703  0.762554
1    0.311540  0.345132  0.751883  0.365315  0.964518
2    0.661391  0.913564  0.580619  0.578853  0.489444
3    0.971994  0.725477  0.171128  0.670740  0.582053
4    0.881631  0.868961  0.173120  0.847732  0.222700
..        ...       ...       ...       ...       ...
329  0.833504  0.488470  0.638519  0.128384  0.921630
330  0.711398  0.888275  0.895772  0.535299  0.823657
331  0.018676  0.350492  0.622680  0.726020  0.975994
332  0.114657  0.763736  0.249243  0.564775  0.467320
333  0.965713  0.121478  0.341810  0.361453  0.267905

[334 rows x 5 columns]

In [34]:
newdf.drop(0,axis=1)

1         2         3         4
0    0.132076  0.223318  0.035703  0.762554
1    0.345132  0.751883  0.365315  0.964518
2    0.913564  0.580619  0.578853  0.489444
3    0.725477  0.171128  0.670740  0.582053
4    0.868961  0.173120  0.847732  0.222700
..        ...       ...       ...       ...
329  0.488470  0.638519  0.128384  0.921630
330  0.888275  0.895772  0.535299  0.823657
331  0.350492  0.622680  0.726020  0.975994
332  0.763736  0.249243  0.564775  0.467320
333  0.121478  0.341810  0.361453  0.267905

[334 rows x 4 columns]

In [35]:
newdf.dropna(inplace=True)